//! Type-safe wrapper for EVM storage mappings (hash-based key-value storage).

use alloy::primitives::{Address, U256};
use std::{
    hash::Hash,
    ops::{Index, IndexMut},
};

use crate::storage::{Layout, LayoutCtx, StorableType, StorageKey, types::HandlerCache};

/// Type-safe access wrapper for EVM storage mappings (hash-based key-value storage).
///
/// This struct does not store data itself. Instead, it provides a zero-cost abstraction
/// for accessing mapping storage slots using Solidity's hash-based layout. It wraps a
/// base slot number and provides methods to compute the actual storage slots for keys.
///
/// # Type Parameters
///
/// - `K`: Key type (must implement `StorageKey`)
/// - `V`: Value type (must implement `StorableType`)
///
/// `Mapping<K, V>` is essentially a slot computation helper. The `[key]` method
/// performs the keccak256 hash to compute the actual storage slot and returns a
/// `Handler` that can be used for read/write operations.
///
/// # Storage Layout
///
/// Mappings use a Solidity-equivalent storage layout:
/// - Base slot: stored in `base_slot` field (never accessed directly)
/// - Actual slot for key `k`: `keccak256(k || base_slot)`
///
/// # Usage Pattern
///
/// The typical usage follows a composable pattern:
/// 1. Create a `Mapping<K, V>` with a base slot (usually from generated constants)
/// 2. Call `[key]` to compute and obtain a `Handler` for that key
/// 3. Use `.read()`, `.write()`, or `.delete()` on the resulting slot
///
/// # Accessing Mapping Fields Within Structs
///
/// When a mapping is a field within a struct stored in another mapping, use the static
/// `at_offset` method to compute the slot without creating a `Mapping` instance:
#[derive(Debug, Clone)]
pub struct Mapping<K, V: StorableType> {
    base_slot: U256,
    address: Address,
    cache: HandlerCache<K, V::Handler>,
}

impl<K, V: StorableType> Mapping<K, V> {
    /// Creates a new `Mapping` with the given base slot number and address.
    ///
    /// This is typically called with slot constants generated by the `#[contract]` macro.
    #[inline]
    pub fn new(base_slot: U256, address: Address) -> Self {
        Self { base_slot, address, cache: HandlerCache::new() }
    }

    /// Returns the U256 base storage slot number for this mapping.
    #[inline]
    pub const fn slot(&self) -> U256 {
        self.base_slot
    }

    /// Returns a `Handler` for the given key.
    ///
    /// This enables the composable pattern: `mapping.at(&key).read()`
    /// where the mapping slot computation happens once, and the resulting slot
    /// can be used for multiple operations.
    ///
    /// The handler is computed on first access and cached for subsequent accesses.
    /// Takes a reference to avoid cloning on cache hits.
    pub fn at(&self, key: &K) -> &V::Handler
    where
        K: StorageKey + Hash + Eq + Clone,
    {
        let (base_slot, address) = (self.base_slot, self.address);
        self.cache
            .get_or_insert(key, || V::handle(key.mapping_slot(base_slot), LayoutCtx::FULL, address))
    }

    /// Returns a mutable `Handler` for the given key.
    ///
    /// Use this when you need to call mutable methods like `write()` or `delete()`.
    ///
    /// The handler is computed on first access and cached for subsequent accesses.
    /// Takes a reference to avoid cloning on cache hits.
    pub fn at_mut(&mut self, key: &K) -> &mut V::Handler
    where
        K: StorageKey + Hash + Eq + Clone,
    {
        let (base_slot, address) = (self.base_slot, self.address);
        self.cache.get_or_insert_mut(key, || {
            V::handle(key.mapping_slot(base_slot), LayoutCtx::FULL, address)
        })
    }
}

impl<K, V: StorableType> Default for Mapping<K, V> {
    fn default() -> Self {
        Self::new(U256::ZERO, Address::ZERO)
    }
}

impl<K, V: StorableType> Index<K> for Mapping<K, V>
where
    K: StorageKey + Hash + Eq + Clone,
{
    type Output = V::Handler;

    /// Returns a reference to the cached handler for the given key.
    ///
    /// The handler is computed on first access and cached for subsequent accesses.
    fn index(&self, key: K) -> &Self::Output {
        let (base_slot, address) = (self.base_slot, self.address);
        self.cache.get_or_insert(&key, || {
            V::handle(key.mapping_slot(base_slot), LayoutCtx::FULL, address)
        })
    }
}

impl<K, V: StorableType> IndexMut<K> for Mapping<K, V>
where
    K: StorageKey + Hash + Eq + Clone,
{
    /// Returns a mutable reference to the cached handler for the given key.
    fn index_mut(&mut self, key: K) -> &mut Self::Output {
        let (base_slot, address) = (self.base_slot, self.address);
        self.cache.get_or_insert_mut(&key, || {
            V::handle(key.mapping_slot(base_slot), LayoutCtx::FULL, address)
        })
    }
}

// Mappings occupy a full 32-byte slot in the layout (used as a base for hashing),
// even though they don't store data in that slot directly.
//
// **NOTE:** Necessary to allow it to participate in struct layout calculations.
impl<K, V> StorableType for Mapping<K, V>
where
    V: StorableType,
{
    const LAYOUT: Layout = Layout::Slots(1);
    type Handler = Self;

    fn handle(slot: U256, _ctx: LayoutCtx, address: Address) -> Self::Handler {
        Self::new(slot, address)
    }
}
